### ISSUE TITLE
Search Coordinates do not work

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#103]
If you make any edition in RapID you can not select search coordinates to transfer to a even near location using Lat/Long data.

ID allow that without problems

**Comment by jeffdefacto** [comment]
Hi @jjiglesiasg,

Can you describe the issue a little more? I'm not entirely sure what you mean by this

Thanks!

**Comment by jjiglesiasg** [comment]
The issue somehow was solved in Version 1.0.7
