### ISSUE TITLE
[Feature] Allow setting the 50 buildng limit higher for experienced mappers

### ISSUE THREAD

**Issue by Atrate** [facebookincubator/RapiD#109]
Once a mapper gets used to contributing via RapiD, it becomes very tedious to have to create a new changeset every couple (50) of buildings.

It would be nice to have a feature that would allow experienced mappers (e.g. 100+ RapiD changesets/500+ OSM changesets overall) to raise the limit to something like 250/500/1000.

Also related to:
#78 
and
#84

**Comment by Atrate** [comment]
A dirty alternative would be to declare AI_FEATURES_LIMIT_NON_TM globally, so it can be modified by tech-savvy individuals

**Comment by jeffdefacto** [comment]
Hey @Atrate 

This is a great idea that we will explore.

Thanks for the suggestion.

**Comment by Bonkles** [comment]
I'm considering something like what tasking manager does- evaluate whether a mapper is advanced or not, and allowing them to configure their preferences accordingly if they're Expert-level.

**Comment by Atrate** [comment]
Yeah, that sounds like the best solution, especially with AI-Assisted HOTOSM getting traction

**Comment by jjiglesiasg** [comment]
Agree; likewise for roads...

**Comment by lkernan** [comment]
+1 for this one.   Even mapping small areas in Australia it feels like you are quickly spamming the changelogs.

**Comment by bhousel** [comment]
RapiD and JUMP (JOSM MapWithAI Plugin) now do have a way to remove the limit for advanced users, but it's not something that we are sharing widely.  

If you're interested in beta testing this and other power features, ping us on the `#mapwithai_feedback` channel on either:
* [OpenStreetMap US Slack](https://slack.openstreetmap.us/)
* [HOTOSM Slack](https://slack.hotosm.org/)

**Comment by boothym** [comment]
Would be good if this could be raised to 100 or 200...
