### ISSUE TITLE
Consecutive duplicate node IDs are being used in buildings

### ISSUE THREAD

**Issue by b-jazz** [facebookincubator/RapiD#131]
Take a look at v1 of the following building: https://www.openstreetmap.org/way/810825393/history#map=19/61.32089/-149.51818

Node 7580906929 appears twice in a row. This triggers various QC tools and asks the community to clean them up. Can this be fixed at the source before entries are added into the database?

**Comment by gaoxm** [comment]
I'll look into this and figure out if it's a data issue or a logic bug from either RapiD or our backend conflation service.

**Comment by gaoxm** [comment]
Confirmed that this is a data issue with the MS building polygons. Working with the MS team on a plan for fix.

**Comment by b-jazz** [comment]
I notice that other imports of building data which I assume to be from MS has the pattern A-B-C-B-D-E-... where the outline goes to a single point and then doubles back on itself. I'm not sure if RapiD is catching and fixing that particular case, but if you're talking with someone about it, you might want to mention it.

**Comment by gaoxm** [comment]
> I notice that other imports of building data which I assume to be from MS has the pattern A-B-C-B-D-E-... where the outline goes to a single point and then doubles back on itself. I'm not sure if RapiD is catching and fixing that particular case, but if you're talking with someone about it, you might want to mention it.

Good catch! Any chance you can find back a specific example?

**Comment by b-jazz** [comment]
https://overpass-api.de/achavi/?changeset=72534341 for https://www.openstreetmap.org/way/706522751 is the clearest example. Also, looking at that example, I don't think it strictly reuses the node, but certainly doubles back on itself and causes a QC issue.

**Comment by mmd-osm** [comment]
You can find similar examples via Overpass by querying for closed ways where the „number of district nodes + 1“ does not equal the „number of nodes“ in that way.

**Comment by gaoxm** [comment]
Update: it will take some time for MS team to do the data cleaning at large scale. We'll add some filtering on FB side to prevent such data from going back to RapiD/JOSM. Expect to get this fixed by end of this week (2020-07-05).

**Comment by gaoxm** [comment]
Fixed on the FB side service. @b-jazz feel free to reopen this if you notice the issue again on #mapwithai changesets.
