### ISSUE TITLE
Rebase onto iD v2.18.x

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#139]
Now that 2.18 is here, we should rebase our public rapid release onto it.

**Comment by bhousel** [comment]
This was done 👍 
In order to sync things back up with openstreetmap/iD, we're going to deprecate the `master` (v3 prototype) branch that was also deprecated upstream.

For the near term future, we'll take the current stable v2.18.x branch, call it `main`, and work off of there.
