### ISSUE TITLE
Exploration: draw map features in canvas layers instead of SVG

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#143]
D3 comes with the ability to render shapes as canvas (raster images) instead of pure svg. This could reap some performance benefits without having to add significant extra dependencies to our stack. 

Possibilities: render the AI features on the map as canvas overlay until they are clicked on, then hide them and display as SVG.  At zoom=16 areas with lots of roads/buildings, this could help performance a lot.

**Comment by bhousel** [comment]
#440 !
