### ISSUE TITLE
Requesting Project Manager Authorization for the tasking manager

### ISSUE THREAD

**Issue by denironyx** [facebookincubator/RapiD#15]
Hi RapiD Team, 

I'm using this medium to request for access to creating tasks with - https://tasks-assisted.hotosm.org/. 

My OSM username is Smart D and I'm currently a project manager for the HOTOSM tasking managers.

**Comment by zlavergne** [comment]
Thanks for your interest @denironyx! 

I've added you as a project manager on the **tasks-assisted** instance.
