### ISSUE TITLE
Design for additional AI sources for buildings & roads

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#152]
Need to make sure that if we get other AI building/road layers, we have a UI design that adequately handles these cases. Right now, we have only one AI road layer (FB Roads) and one AI building layer (Microsoft).

**Comment by bhousel** [comment]
This is done, we have buildings available in many Esri provided datasets now  🎉 
Some changes are coming soon to the dataset view/manage screen to better scale to handle the number of datasets we have.
