### ISSUE TITLE
Panning map slower than iD

### ISSUE THREAD

**Issue by jidanni** [facebookincubator/RapiD#154]
Some areas to work on:
Dragging the map around has a definite delay compared to iD.
Also zooming in and out with the mouse: it is still zooming in while in the meantime we have already begun zooming back out.

**Comment by Bonkles** [comment]
Agreed that RapiD could be rendered faster- we have two things working against us regarding RapiD performance: 
1) RapiD tries to render more than iD, on account of all the extra shapes it is drawing on the screen. 
2) RapiD also has a lot more to load than iD from third party API services- specifically, each time the user pans or scrolls, we need to query the back-end for any feature shapes that need to be drawn. 

Performance in general is bubbling to the top of our priority list in 2021. 

Just curious- have you tried turning the RapiD layer completely off (Shift+R) and observing the same slowdowns? It's also possible that the version of iD you were using had slightly different code than the RapiD version has- sometimes bugfixes can make things snappier, and we can lag behind state-of-the-art iD a bit.

**Comment by jidanni** [comment]
(I'm sorry I'm not using this anymore, so can't help. But yes iD is "nice and slow" for me too.)

**Comment by bhousel** [comment]
I just did some profiling with the most recent RapiD 1.1.1 and iD 2.19.5 and the performance looks nearly identical, so I think we're good to close this.  Screenshots below show what the browser is doing panning across the same 3 screens of tiles at zoom 18.

Compared to main iD, RapiD will use the network a bit more and render possibly a lot more features if external data layers like roads and buildings are enabled (but the user can turn these layers off).

I have some other things planned for improving RapiD's performance, such as using worker threads for deferred work and webgl canvas for speedier rendering. 

### RapiD 1.1.1
<img width="1667" alt="Screen Shot 2021-02-09 at 12 29 27 PM" src="https://user-images.githubusercontent.com/38784/107403049-a642bc80-6ad2-11eb-98d6-7cce3846b8d9.png">

### iD 2.19.5
<img width="1668" alt="Screen Shot 2021-02-09 at 12 29 42 PM" src="https://user-images.githubusercontent.com/38784/107403088-b5c20580-6ad2-11eb-95c6-00e6430943ba.png">
