### ISSUE TITLE
RAPID 1.1.0-pre 2 Right Click menu always on

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#160]
![Screenshot 2020-08-22 22 01 11](https://user-images.githubusercontent.com/22849578/90969169-85a28e00-e4c3-11ea-82e6-b13903905b23.png)

The right click displayable menu, remains on, even without any feature selected...

**Comment by jjiglesiasg** [comment]
Now up to five bars floating
![Screenshot 2020-08-23 20 10 35](https://user-images.githubusercontent.com/22849578/90992324-f35ec080-e57c-11ea-8309-ebff050d9d15.png)

**Comment by bhousel** [comment]
This seems to be something upstream that's since been fixed
https://github.com/openstreetmap/iD/issues/7528
https://github.com/openstreetmap/iD/issues/7143
