### ISSUE TITLE
Many wrong features in a sector of the municipality of Frontino, department of Antioquia Colombia.

### ISSUE THREAD

**Issue by JLOSM** [facebookincubator/RapiD#178]
https://mapwith.ai/rapid#background=Maxar-Premium&disable_features=boundaries&map=17.25/6.77153/-76.17401

**Comment by jeffdefacto** [comment]
Hi @JLOSM 

Looks like this area has cloud cover in our imagery. We'll rerun it once we get some newer imagery for prediction.

Thanks for letting us know!

![image](https://user-images.githubusercontent.com/17914981/93799740-6a2ac000-fbf4-11ea-850c-3c11bce2cb73.png)

**Comment by JLOSM** [comment]
En la zona donde reporte, no existen nubes en las imágenes de Maxar.
No me concuerda con la respuesta.

________________________________
De: jeffdefacto <notifications@github.com>
Enviado: lunes, 21 de septiembre de 2020 12:23 p. m.
Para: facebookincubator/RapiD <RapiD@noreply.github.com>
Cc: JLOSM <jlopez798@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [facebookincubator/RapiD] Many wrong features in a sector of the municipality of Frontino, department of Antioquia Colombia. (#178)


Hi @JLOSM<https://github.com/JLOSM>

Looks like this area has cloud cover in our imagery. We'll rerun it once we get some newer imagery for prediction.

Thanks for letting us know!

[image]<https://user-images.githubusercontent.com/17914981/93799740-6a2ac000-fbf4-11ea-850c-3c11bce2cb73.png>

**Comment by jeffdefacto** [comment]
Hey @JLOSM 

Current Maxar Premium has captured this area with clear satellite, but our internal version of the imagery was ingested some time ago and, as you can see in the screenshot above, its cloudy in that area.

Once we ingest the latest imagery from Maxar, it should match what you see in the public Maxar Premium layer.

**Comment by gaoxm** [comment]
thanks for the follow up @jeffdefacto - I guess we can keep this issue open until our ML roads data is updated for the area, **after** our imagery is updated.
