### ISSUE TITLE
RapiD is leaking browser tab information into the 'imagery_used' saved changes.

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#186]
OSM User `Ika-chan!` reported this issue via openstreetmap's FB email. 

It seems that they have two changesets where browser tab information somehow leaked into the 'imagery_used' field. Here are the changesets: 

First occurance: 
https://www.openstreetmap.org/changeset/94522354

Second: 
https://www.openstreetmap.org/changeset/94649123

I did a search on osmcha.org for any similar issues with 'Editor: RapiD 1.0.12' and `source_imagery: parentId` and these are the only two issues that appear. 

![image](https://user-images.githubusercontent.com/1887955/100266634-25871200-2f20-11eb-824d-986724b3eaf4.png)

![image](https://user-images.githubusercontent.com/1887955/100266692-3768b500-2f20-11eb-9ee6-642d561ac2b8.png)

**Comment by Bonkles** [comment]
User reported the following addons installed in Firefox 83: 
Firefox reports the following add-ons, some of which are built-in:

Name: British English Dictionary (Marco Pinto) Type: dictionary Version: 2.90 Enabled: true ID: marcoagpinto@mail.telepac.pt

Name: English United States Dictionary Type: dictionary Version: 78.0 Enabled: true ID: @unitedstatesenglishdictionary

Name: Amazon.co.uk Type: extension Version: 1.3 Enabled: true ID: amazon@search.mozilla.org

Name: Bing Type: extension Version: 1.2 Enabled: true ID: bing@search.mozilla.org

Name: BlockTube Type: extension Version: 0.3.18 Enabled: true ID: {58204f8b-01c2-4bbc-98f8-9a90458fd9ef}

Name: Chambers (UK) Type: extension Version: 1.0 Enabled: true ID: chambers-en-GB@search.mozilla.org

Name: DuckDuckGo Type: extension Version: 1.1 Enabled: true ID: ddg@search.mozilla.org

Name: eBay Type: extension Version: 1.2 Enabled: true ID: ebay@search.mozilla.org

Name: Enhancer for YouTube™ Type: extension Version: 2.0.101 Enabled: true ID: enhancerforyoutube@maximerf.addons.mozilla.org

Name: Google Type: extension Version: 1.1 Enabled: true ID: google@search.mozilla.org

Name: Iridium for YouTube Type: extension Version: 0.2.5 Enabled: true ID: unlisted-iridium@particlecore.github.io

Name: LeechBlock NG Type: extension Version: 1.0.7.2 Enabled: true ID: leechblockng@proginosko.com

Name: SponsorBlock for YouTube - Skip Sponsorships Type: extension Version: 2.0.8 Enabled: true ID: sponsorBlocker@ajay.app

Name: Tampermonkey Type: extension Version: 4.11.6120 Enabled: true ID: firefox@tampermonkey.net

Name: uBlock Origin Type: extension Version: 1.31.0 Enabled: true ID: uBlock0@raymondhill.net

Name: uMatrix Type: extension Version: 1.4.0 Enabled: true ID: uMatrix@raymondhill.net

Name: Wikipedia (en) Type: extension Version: 1.1 Enabled: true ID: wikipedia@search.mozilla.org

Name: Adobe Acrobat Type: extension Version: 18.0.10 Enabled: false ID: web2pdfextension.17@acrobat.adobe.com

Name: NoScript Type: extension Version: 11.1.5 Enabled: false ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

Name: Privacy Pass Type: extension Version: 2.0.6 Enabled: false ID: {48748554-4c01-49e8-94af-79662bf34d50}

**Comment by Bonkles** [comment]
We got a data dump from the user with screenshots of the local browser storage at the time of bug reproduction! :trumpet:

Unfortunately, it didn't give me any clues into why this behavior is happening. 😢  It's looking less and less likely that I'll be able to reproduce this one.

**Comment by bhousel** [comment]
Closing for now, but we can revisit if it happens again.
94ac8d1ca improved the logic a bit for setting imagery and source tags.
