### ISSUE TITLE
"Connect the feature" repurposes stop node

### ISSUE THREAD

**Issue by atiannicelli** [facebookincubator/RapiD#194]
Situation:
I had a place where there was a road that crossed a footpath and there was no node so RapID warns that the two ways cross without a node - all good.

The Issue:
When I click on the "Connect the features" it took a stop node on the road that was close to the crossing and moved it and made it into a crossing (and stop) node. 

What I expected:
I would think that we would not want to combine stop and crossing nodes when connecting ways since the stop is specific to the car navigable highway and should not be on the pedestrian highway because there is no stop on the pedestrian way. I think that a new node should have been created at the intersection with highway=crossing and then the stop node should have been left alone.

Here is the editor before I clicked "Connect the feature"
![Screen Shot 2021-01-08 at 12 58 21 PM](https://user-images.githubusercontent.com/5851115/104053694-b4db4280-51b9-11eb-9513-cd243a9fa300.png)
And here is the editor after I clicked "connect the feature" and after I clicked on the node so you can see the tags assigned to it.
![Screen Shot 2021-01-08 at 12 59 19 PM](https://user-images.githubusercontent.com/5851115/104053713-bad12380-51b9-11eb-8676-e827cab4f59b.png)

**Comment by bhousel** [comment]
Thanks for reporting @atiannicelli  - this is actually in issue upstream in openstreetmap/iD.
I'll try to move the issue there..
