### ISSUE TITLE
Lots of flashing happening with the new dark sidebar as the user moves the mouse quickly over AI features

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#196]
The 1.1.0 Esri release saw a 'dark mode' RapiD bar get introduced, which looked great in isolation but also causes a lot of 'flashing' between dark and light modes when the user scrolled the mouse over a lot of AI / Esri features at once.

**Comment by bhousel** [comment]
this was done in 77e78eec3
