### ISSUE TITLE
UX: Should we hide the pink line when selecting / before approving ?

### ISSUE THREAD

**Issue by amenk** [facebookincubator/RapiD#23]
I see a problem with the AI lines: They are on top of the satellite image and so cover the actual road feature, making it sometimes hard to decide if there is a road and may lead to false positives.

Currently the pink AI lines can be toggled with Shift+R, but I doubt lots of people are doing that.

Maybe we could hide the line on mouse over and only show the "halo", a bit more far away from the actual feature, so that the full feature is visible and not obscured by the line, avoiding false positives?

**Comment by Bonkles** [comment]
I like the idea behind this line of thinking! 

I've attached a .gif of how something like this might work- just a simple opacity animation purely in .css. 

![on_off_startnode_building](https://user-images.githubusercontent.com/1887955/63280503-eaa42200-c278-11e9-8196-b4de63851bfe.gif)

If the road isn't selected, we pulse the visibility of the AI road to show the satellite imagery underneath.

**Comment by amenk** [comment]
I was more thinking about less animation and finding some way of statically showing what is selected, but yeah, this might work as well

**Comment by Bonkles** [comment]
Understood- thanks for the feedback. I'll bring this up with the rest of the RapiD team in our next sync!

**Comment by govvin** [comment]
To help deal with this issue, we highlighted several iD keyboard shortcuts during on-boarding for contributors in sessions we organize:
Shift+R - Toggle detections
ALT+W - Toggle OSM data
W - Toggle OSM data fill

Visualizing detections as pulsing features seems interesting.

**Comment by Bonkles** [comment]
We are going to circle the wagons prior to iD v3 releasing (which we're keeping close tabs on and are dogfooding internally). Expect some upgrades to how roads are added to the map in the near future.
