### ISSUE TITLE
Saving work hangs

### ISSUE THREAD

**Issue by FransS1945** [facebookincubator/RapiD#3]
After re-tagging of a highway I wanted to upload it. ( Logged in on osm)  Screen display becomes darker gray, nothing was saved. A few moments later the screen becomes black

**Comment by gaoxm** [comment]
@FransS1945 thanks for submitting this! However I was unable to reproduce the "not savable" issue - did you just hit the gray UI interface for adding changeset comments before uploading to OSM? see below:

![image](https://user-images.githubusercontent.com/7350578/62237884-d23e9700-b39f-11e9-9e6e-334f9a4130d6.png)

![image](https://user-images.githubusercontent.com/7350578/62237863-c6eb6b80-b39f-11e9-9127-42d8ef07153a.png)

Let me know if you could share a little more about how to reproduce the issue :)

**Comment by bhousel** [comment]
closing as stale - I think this was likely fixed already.
