### ISSUE TITLE
"Connect the features" function doesn't work

### ISSUE THREAD

**Issue by arch0345** [facebookincubator/RapiD#300]
iD suggests to 'connect the features' when highways cross over each other. When I click on 'connect the features' when this issue pops up, instead of adding a node connected to both highways, nothing happens. This only seems to happen in RapiD 1.1.6 and not the version of iD on osm.org/edit.

**Comment by jjiglesiasg** [comment]
The same is happening in 1.1.6 when a road cross a waterway, the system suggest to create a shared node tagged as "Ford" but no connection or node are created once selected...

**Comment by bhousel** [comment]
Thanks for reporting this - I can confirm I get the same thing.. 👍

**Comment by jjiglesiasg** [comment]
This issue is still happening, also the cursor is unresposive and you can't select becuase goes to the + indication of new drawing.

First time that an issue of editing preclusion is happening for such a long time...

**Comment by arch0345** [comment]
> This issue is still happening, also the cursor is unresposive and you can't select becuase goes to the + indication of new drawing.
> 
> First time that an issue of editing preclusion is happening for such a long time...

This will probably be fixed once 1.1.7 is released
