### ISSUE TITLE
Country request: Russia

### ISSUE THREAD

**Issue by Vovenarg** [facebookincubator/RapiD#31]
I would like to request Russia  ##be added to your queue, thanks!

**Comment by danil-kirsanov** [comment]
Added to the country list, thank you.

**Comment by Bonkles** [comment]
@Godnik from geoalert.io has also requested russian road data.

**Comment by Godnik** [comment]
Thanks Ben for adding our request

**Comment by jeffdefacto** [comment]
Russia is now available.

Happy mapping!
