### ISSUE TITLE
Investigate slowdowns of the RapiD layer rendering

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#395]
One of our internal users has found that RapiD's performance goes to heck in a handbasket in certain areas using Safari. 

Example repro URL: 
https://mapwith.ai/rapid#background=USGS-Scanned_Topographic&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w851407605&map=17.00/37.28717/-118.38717

I took a trace using safari here and, sure enough, panning/scrolling causes a very laggy experience.  

Safari recording is attached:
[mapwith.ai-recording.json.zip](https://github.com/facebookincubator/RapiD/files/7539975/mapwith.ai-recording.json.zip)
 
 Screenshot of representative section of the trace: 
![image](https://user-images.githubusercontent.com/1887955/141815316-7f90d9d3-8159-43cf-8b63-fe4c69071e77.png)

**Comment by LonelyRobot13** [comment]
I'm having the same issue on windows

**Comment by Bonkles** [comment]
After some further investigation, I found the following: 
* The more dense the .svg, the worse safari's performance gets. This still occurs with normal iD, not just RapiD- areas such as the one in the bug description are simply filled with many more features with all the RapiD layers turned on, so it *seems* like a rapid problem.  
* Safari's performance while panning/zooming the map seems to be the worst out of all the major browsers. Chrome and Edge seem to be somewhere in the middle, whereas Firefox rendering is fastest, blowing everybody else out of the water. This seems to be because of some mouse handling tricks that firefox does- while the page is being dragged/zoomed around, it makes many fewer attempts to render the SVG, which means it spends zero time sending vertices to the rendering pipeline to transform, and as such is more performant.  Safari seems to attempt to re-render the page every ms or so while panning, causing our renderer to get crushed.

**Comment by Bonkles** [comment]
In short, problems like this will persist and be at the mercy of the individual browser implementation for SVGs. If Safari wants to re-render the entire map dataset every time the user pans so much as half a pixel, it will do so and we can't really fix it. 

What we *CAN* do to fix this is replace the native SVG map renderer with something else. Which may or may not be something that we're actively developing. 🤐

**Comment by bhousel** [comment]
> What we _CAN_ do to fix this is replace the native SVG map renderer with something else. Which may or may not be something that we're actively developing. 🤐

The cat's out of the bag!  #440 is where we are headed with this  🎉
