### ISSUE TITLE
Bug at login as user on OSM through  TM3 

### ISSUE THREAD

**Issue by FransS1945** [facebookincubator/RapiD#4]
Tried to open a task through the HOT OSM route. 
 after opening TM3  I need to login to Hotosm.  I have an account. So normally that works fine.
Now, when clicking on a project.  I selected project 3 After clicking on the mapping field I am asked first to log in, 
Selected the shortcut gives the next result
https://tasks-assistedv2.hotosm.org/api/v1/auth/oauth-callback?redirect_to=/project/3&oauth_token=C42GNuLKLZkp5jKvRSTQeCjs4viOdMVuwM4hByl7&oauth_verifier=Lungs1mBfB1D4xPJKupr 
and ended up in an emty screen with the text  'nul'
That's it.  No I D editor

**Comment by jeffdefacto** [comment]
This has been resolved on the tasking manager side.
