### ISSUE TITLE
Can't save or upload

### ISSUE THREAD

**Issue by Fizzie41** [facebookincubator/RapiD#400]
Hi. Just using RadiD (1.1.8), pretty well for the first time, & using it to map buildings via Microsoft Buildings.

Got to change 51 & it stopped responding with a message that I need to save when reaching 50 edits.

Have tried several times to do so, but as soon as I hit either the Save button, or ctrl-s, a blank Firefox screen appears, with a rotating cycling icon hidden behind it.

After a few seconds, the cycling symbol disappears, & the normal OSM "Authorize access to your account" page comes up. 

When I click on "Grant Access", another blank Firefox window appears: 
https://mapwith.ai/land.html?oauth_token=lS6LLGYmcc4Q3l9eLO9OpyuDr08CzxsFZrqG9aXO
& everything freezes at that, but the mapping screen has been greyed out. 

When I manually close that Firefox window, the map screen is greyed out & mousing over the Save button shows an unavailable red circle.

It didn't open the usual Changeset Comment page at all.

The only thing I can then do is close the entire window, which asks if I want to leave the page. When I then reopen RapiD, it asks if I want to restore my changes from a previous session, but the same problem continues

I tried deleting the last change I made to reduce it to 50, & then another to 49, but no change.

Using Firefox 94.0.1 & Windows 10.

Thanks

**Comment by Fizzie41** [comment]
Should also add that I have the Facebook Container extension activated, but it appears that the RapiD page is opening normally?

**Comment by tsmock** [comment]
> Should also add that I have the Facebook Container extension activated, but it appears that the RapiD page is opening normally?

It looks like it is due to having the Facebook Container extension activated. Rather unfortunately, I doubt that we will be able to fix this, as the whole point of the Facebook Container extension is to prohibit sharing of information (e.g. login credentials) between other sites and Facebook.
Workaround: Temporarily disable it while you log in to RapiD.
Alternate workaround: Use the "Allow Site in Facebook Container" action on https://openstreetmap.org (click on the fence icon for "Facebook Container", if you don't see it, you may have to figure out where you put it).

**Comment by Fizzie41** [comment]
Thanks.

After quite a bit of playing, it appears that the only way I can use RapiD is by giving Facebook access to everything that I do on OSM, which is not what I want :-(

Appears that I may have to keep doing things the old manual way!

Thanks

**Comment by tsmock** [comment]
You can remove https://openstreetmap.org from the `Allow Site in Facebook Container` after authentication. So you don't need to give Facebook access to everything you do on OSM. All that aside, I don't think OSM has any Facebook API calls, outside of using Facebook OAuth to log into OSM.

Alternatively, you can try using the JOSM MapWithAI plugin (disclaimer: I maintain that plugin).

**Comment by bhousel** [comment]
I'd like to look into this issue some more - from what I see RapiD isn't and shouldn't be using any special Facebook services to perform the OAuth with OSM. 

> it appears that the only way I can use RapiD is by giving Facebook access to everything that I do on OSM, which is not what I want :-(

It's not what we want either!  I dont think this is how it works at all, but please give us the opportunity to investigate.

**Comment by tsmock** [comment]
As I noted earlier, I don't think we can fix this.

See https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L9-L33, specifically https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L26. `mapwith.ai` is explicitly added to the `FACEBOOK_DOMAINS` array, which means there is nothing we can do, as we are automatically added to the container.

We can ask the Facebook Container team to make an exception for communication between osm.org and mapwith.ai, but I give it _really good odds_ that they will not.

**Comment by bhousel** [comment]
Thanks @tsmock I didn't realize this was about the "Facebook Container" extension.  Yes it's outside our control.

Another workaround is people can edit with the https://ideditor.org/rapid mirror if they want to use an up to date version of RapiD that's not hosted on the mapwith.ai domain.

**Comment by tsmock** [comment]
Your workaround also will not "work" -- see https://github.com/mozilla/contain-facebook/issues/551 (rapid makes requests to facebook.com/maps/ml_roads , which is blocked, as ideditor.org is not a FB domain, so you have to add it to the FB Container, which in turn means that you cannot login, without having logged in previously).

But yes, this is completely outside our control.

Again, workarounds I've tested:
1. Disable Facebook Container, log in, enable Facebook Container
2. Use `Allow Site in Facebook Container` to add osm.org to the Facebook Container, log in, use `Remove Site from Facebook Container` to remove osm.org from the Facebook Container
3. Use JOSM with the MapWithAI plugin

With 1. or 2., you will have to follow that process every time you want to log in. So if you have your browser set to clear logins/cookies/whatever iD uses for login information, you will have to do this process every time you want to log in.

**Comment by bhousel** [comment]
> Your workaround also will not "work" -- see [mozilla/contain-facebook#551](https://github.com/mozilla/contain-facebook/issues/551) (rapid makes requests to facebook.com/maps/ml_roads , which is blocked, as ideditor.org is not a FB domain, so you have to add it to the FB Container, which in turn means that you cannot login, without having logged in previously).

How were they able to add 50 Microsoft buildings if the extension was blocking the calls to ml_roads?

**Comment by tsmock** [comment]
Sorry, communication. `mapwith.ai` was added to the Facebook Container so that it could reach the `ml_roads` endpoint. But since it was added to the container, it can no longer communicate with OSM OAuth, so it cannot upload.

**Comment by Fizzie41** [comment]
> You can remove https://openstreetmap.org from the `Allow Site in Facebook Container` after authentication. So you don't need to give Facebook access to everything you do on OSM. All that aside, I don't think OSM has any Facebook API calls, outside of using Facebook OAuth to log into OSM.

Update to say that this (apparently?) worked :-)

Allowed OSM to be included, then removed it again.

Opened RapiD (which didn't ask me to login with OSM details?) added more buildings & saved them OK.

OSM is showing that Facebook Container is operating, but despite not logging in, those additions are showing as my latest changesets when I check my OSM profile, so not too sure how that works?

But all looks good, so thanks very much!

**Comment by LaoshuBaby** [comment]
I also meet with this, after click auth and only a blank window left, this only happen in firefox and I noticed rapid is running in a facebook container tab, so maybe this editor using something from facebook, and blocked by firefox.

But, when I open a privacy window, the facebook container still working and I can login successfullly, so if you meet with same problem you can try this
(The only disadvantage is you need to login everytime when open a privacy window because no cookies will be saved)

![图片](https://user-images.githubusercontent.com/42690037/201530185-22851b7e-9725-449d-a905-affc29918786.png)

**Comment by LaoshuBaby** [comment]
> Another workaround is people can edit with the https://ideditor.org/rapid mirror if they want to use an up to date version of RapiD that's not hosted on the mapwith.ai domain.

According to just recently test, ideditor.org also blocked by this extension.
