### ISSUE TITLE
False-positive warning for Google Africa Buildings dataset

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#403]
Twitter user `@s3lf` sent this one in: 

Edit: I created a sister PR over in the iD repo: https://github.com/openstreetmap/iD/pull/8844

![image](https://user-images.githubusercontent.com/1887955/145423079-fad11cc8-c656-4946-8c26-fc85b4aac9c8.png)

Need to figure out what's triggering this warning and fix it.

**Comment by bhousel** [comment]
Oh this is coming from the `incompatible_source.js` validator:
https://github.com/openstreetmap/iD/blob/develop/modules/validations/incompatible_source.js

We need to add an exception for the Google buildings dataset, both in RapiD and iD:
https://github.com/openstreetmap/iD/blob/ab8a07fb45d238c202f406faa08bb6e2b13c849c/modules/validations/incompatible_source.js#L17-L21

**Comment by Bonkles** [comment]
Fix is made to both iD and RapiD, should go out in next release of both apps.
