### ISSUE TITLE
Country request: Galapagos (Ecuador)

### ISSUE THREAD

**Issue by cbeddow** [facebookincubator/RapiD#41]
I'd like to see how this works specifically in the Galapagos Islands of Ecuador

**Comment by gaoxm** [comment]
thanks @cbeddow ! added to https://github.com/facebookincubator/RapiD/blob/master/COUNTRY_REQUESTS.md

**Comment by jeffdefacto** [comment]
@cbeddow Ecuador, including the Galapagosm is now available!
