### ISSUE TITLE
Publish roads tiles to editor-layer-index

### ISSUE THREAD

**Issue by Komzpa** [facebookincubator/RapiD#44]
https://github.com/osmlab/editor-layer-index is a way to share layers and make them accessible in any editor. We are also pulling it in for disaster.ninja project, which helps HOT decide on how to do the next activation. Would be great to see the pink roads layer available there, given its license is good for going into OSM anyway.

**Comment by gaoxm** [comment]
@Komzpa great idea 👍! We will look to add it there

**Comment by bhousel** [comment]
Going to close this as out-of-scope for now - the roads data is available as vector data in RapiD and JUMP (JOSM MapWithAI Plugin), and we'd need to convert it to raster data in order to share it elsewhere.  If we do revisit this issue, we'll let you know!
