### ISSUE TITLE
New WebGL-based renderer for RapiD!

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#440]
Last week @Bonkles and I gave a talk at the [State of the Map US conference](https://2022.stateofthemap.us/) where we shared some details about our work on a _new_ WebGL-based renderer for RapiD built on the open source [PixiJS](https://pixijs.com/) game engine.  🎉 

The new WebGL-based renderer will allow RapiD to keep up with the increasing demands placed on it, as OpenStreetMap aims to map the world at greater levels of detail. Many places where RapiD was previously unusable now become responsive even at low zooms.

You can try out this new speedier RapiD at this link, where we will push updates sometimes:
https://mapwith.ai/rapid-sotm-2022

_This is an "alpha" release_ and there are for sure lots of bugs that need to be squashed.  We'll start tracking bugs and issues related to the new RapiD on this GitHub, with the label https://github.com/facebookincubator/RapiD/labels/webgl . If you find a bug, let us know!

We don't have a set deadline for when this work will replace the currently deployed RapiD, but we expect it will happen this year sometime, fingers crossed! 🤞 

Also - anyone interested in digging into the code more closely is encouraged to check out the `pixi_playground` branch.
https://github.com/facebookincubator/RapiD/tree/pixi_playground

Here are some links on Twitter that you can share too:  
https://twitter.com/MapWithAI/status/1510028065824391168
https://twitter.com/bhousel/status/1510053741025656835

And a short video showing the difference between the old and new renderer.
https://user-images.githubusercontent.com/38784/162043618-d3281c9a-5344-4e88-874c-b550f92684b5.mov

(We'll post a link to our talk whenever it is available)

Finally, please to reach out to us (Ben Clark, Bryan Housel) on [OSM-US Slack](https://slack.openstreetmap.us/) if you want to discuss more.  
We're always happy to have a conversation!

I'd also like to especially thank @sketchpunk, @vanreece, @danil-kirsanov, and the folks at @PixiJS team whose patience and work made this possible!  🙌

**Comment by jjiglesiasg** [comment]
Hi Bryan, it looks nice, I tryed to make some edition of ways, and it allows you to select a road, but Do Not show the nodes of such road, neither allow you o move or edit any segment of he road. Standalone nodes (places, schools) etc, could be edited the data tags, but not moved as well. 
Eager to see more, and have the Data Suggestion for #Bolivia back on line. Best Regards
JJ

**Comment by Bonkles** [comment]
> Hi Bryan, it looks nice, I tryed to make some edition of ways, and it allows you to select a road, but Do Not show the nodes of such road ...

Thanks for trying it out @jjiglesiasg ! We are keenly aware that this version of RapiD needs additional work before it's 'polished' enough to use. For now, we appreciate anybody trying it out to ensure that it renders no matter the device. 

Full edit Interactivity will come later. To the moon! 🌔

**Comment by bhousel** [comment]
> Do Not show the nodes of such road, neither allow you to move or edit any segment of the road.

FYI I added this to #452 - currently we're only rendering "interesting" vertices, but we need to show all the vertices once a way becomes selected.

**Comment by bhousel** [comment]
> (We'll post a link to our talk whenever it is available)

The recording of talk is now available!

Share on Twitter:  https://twitter.com/sotmus/status/1519353707326017538
Link to the talk on YouTube:  https://www.youtube.com/watch?v=Kn7qusvEynU

**Comment by Bonkles** [comment]
Closing this issue as I have opened a Discussion on the same topic: #481.
