### ISSUE TITLE
Missing features from Rapid v2

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#452]
A catch-all issue for stuff that is currently missing from the rapid v2 alpha that we should to put back.  Most of this stuff is related to how things get styled as the user interacts with the map. For some of these it might nice to do something cool/fun that we couldn't do before with the old renderer:

- [ ] fix hovering
- [ ] move operation
- [x] showing "boring" vertices and midpoints when a way is selected
- [ ] selected/hovered streetview imagery traces and images
- [ ] labeling/icon for polygons (maybe improved rendering of POI-mapped-as-polygon)
- [x] selected/hovered QA issues
- [ ] fix or simplify all the select "modes" for data/osm/rapid/qa/etc (do we really need all these)
- [x] gpx/geojson traces and other user-supplied data?
- [ ] showing relation membership
- [x] background imagery filters (brightness, contrast, saturation, sharpen)
- [ ] style for ephemeral features (abandoned, proposed, construction, intermittent, etc)
- [x] style for directional features (cliff, coastline, retaining_wall, kerb, etc)
- [ ] the turn restriction editor
- [x] the minimap

(ordered highest to lowest priority)

We can add to this list or check stuff off as we complete them.  (I think we're ok if we launch v2 without a minimap)

**Comment by Bonkles** [comment]
custom data gpx/geojson traces are once again uploadable to the map.  You can supply them in the `gpx` URL param as before, drag and drop them on top of the map, or use the selector UI to find a file on your local hard drive. 

introduced in commit ec6d47490. 
![custom_data_working](https://user-images.githubusercontent.com/1887955/172713549-34f74ac7-6492-4be9-8b7f-0976af7f51bd.gif)

**Comment by Bonkles** [comment]
Minimap is covered by https://github.com/facebookincubator/RapiD/pull/480, which was just merged.

**Comment by Bonkles** [comment]
Style for 'sided' features (kerbs, retaining wall, city wall, weirs, etc) is done, added in commit 9ed485cd5.

![image](https://user-images.githubusercontent.com/1887955/174339145-2e0c64e8-6206-429a-8c4f-b8238c5ee623.png)

**Comment by Bonkles** [comment]
We've split this task out into several smaller tasks. Closing!
