### ISSUE TITLE
Measurement Panel broken in v2

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#455]
`projectionStream` is not a function during centroid calculation
called here:
```js
  centroid = d3_geoPath(context.projection).centroid(entity.asGeoJSON(graph));
```

![Screen Shot 2022-04-19 at 4 59 46 PM](https://user-images.githubusercontent.com/38784/164094806-5f2f5364-3e78-421e-931d-a090072a88e2.png)

Update: this issue looks like it has morphed, the panels 'work' now but are instead reporting that they cannot access the localized label text.

**Comment by Bonkles** [comment]
This issue has been fixed already.
