### ISSUE TITLE
Country Request: Somalia

### ISSUE THREAD

**Issue by AleZena** [facebookincubator/RapiD#47]
Hello, the U.N. G.I.S. section is working to map southern part of Somalia (https://wiki.openstreetmap.org/wiki/UN_Maps_Project).
Would be nice test your AI on buildings and roads.

Many thanks
  Alessandro

**Comment by gaoxm** [comment]
added to https://github.com/facebookincubator/RapiD/blob/master/COUNTRY_REQUESTS.md

**Comment by jeffdefacto** [comment]
Somalia is now available
