### ISSUE TITLE
v2: Global search does not zoom on selected location

### ISSUE THREAD

**Issue by tordans** [facebookincubator/RapiD#471]
To reproduce: 

1. Open https://mapwith.ai/rapid-sotm-2022#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/54.2/10.4 which shows the world
2. Search for "Rixdorf, Germany",
3. Click first entry "village"
4. ==> Should zoom to the location; does nothing

Don't see anything on the console; Some locations do move the map a tiny bit, but don't zoom; Network tab shows successful request on click.

**Comment by Bonkles** [comment]
Let's get this retested before our upcoming sotm / foss4g release alpha.

**Comment by Bonkles** [comment]
It looks like if the shape of the searched entity is too large (i.e. a very large relation, admin boundary for a county etc) then it doesn't get displayed until the user zooms in. 

That said, the map will zoom to the feature in question now- tested on oslo, tokyo, rapid city SD.
