### ISSUE TITLE
v2: Style options

### ISSUE THREAD

**Issue by tordans** [facebookincubator/RapiD#473]
Update: The change only takes effect after reloading the UI.

The new version does not yet have the style options and probably the custom "highlight changes" style, yet.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/111561/167303212-0f7b15d5-435b-4f7e-9cb0-8342666d24b1.png">

[Testlink](https://mapwith.ai/rapid-sotm-2022#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.96/52.47342/13.44849)

**Comment by Bonkles** [comment]
We are tracking the 'highlight changes' in #509 and this will probably come in sometime after v2 releases. 

The rest should be fixed in our upcoming 2.0 alpha release.
