### ISSUE TITLE
Country Request: Uganda

### ISSUE THREAD

**Issue by Melegy90** [facebookincubator/RapiD#50]
Hello,

Great work people! **Uganda** has a highly active OSM community and Kampala the capital is seeing a lot of infrastructure development at the moment, especially with the Bus Rapid Transport (BRT) implementation. Including Uganda in RapiD would immensely help with the mapping efforts there.

**Comment by gaoxm** [comment]
@Melegy90 thanks for asking about Uganda - we actually have already released AI-generated roads there! Here is an area near Kampala where I can find some AI roads complimentary to OSM:
https://mapwith.ai/rapid#background=Maxar-FB&disable_features=boundaries&map=17.00/0.31185/32.55307

Also, if you are used to using HOT tasking manager, there is an experimental TM server at https://tasks-assisted.hotosm.org/contribute?difficulty=ALL, where you can create projects and enable RapiD as one editor option by default! Just let us know if you want to become a project manager there. I see the Kampala area is pretty dense so limiting task size to smaller than 1km * 1km would help with RapiD's performance.

Happy mapping!
