### ISSUE TITLE
can't interact with way midpoints

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#538]
Update: midpoints were turned off temporarily while we attend FOSS4G.

**Comment by alesarrett** [comment]
I confirm the issue is still there and it makes it impossible to modify existing geometries (and also refine new ones).

**Comment by Bonkles** [comment]
Fixed in `400aa6612`. 

There are still some places where the midpoints aren't being rendered correctly- will open a separate bug for that. The midpoint dragging behavior is restored at least! proof: 



![Image](https://user-images.githubusercontent.com/1887955/201435319-e2d3976d-ec9b-472d-8a59-3d3051d5ae73.gif)
