### ISSUE TITLE
Country Request: Haiti

### ISSUE THREAD

**Issue by mapninja** [facebookincubator/RapiD#55]
We are working to improve access to nighttime healthcare in rural Haiti. Our project is MotoMeds, and would benefit from better maps of buildings and roads in the Gressier, and Leogane communes. [https://www.trekmedics.org/programs/haiti/motomeds-healthline-for-sick-children-haiti/](https://www.trekmedics.org/programs/haiti/motomeds-healthline-for-sick-children-haiti/)

[Gressier_Leogane_ADM4.geojson.zip](https://github.com/facebookincubator/RapiD/files/3719978/Gressier_Leogane_ADM4.geojson.zip)

**Comment by jeffdefacto** [comment]
Thanks for the request @mapninja 

I've added Haiti to the list

**Comment by jeffdefacto** [comment]
@mapninja Haiti is now available!
