### ISSUE TITLE
Log-in Bug

### ISSUE THREAD

**Issue by yeminator** [facebookincubator/RapiD#550]
### Description

OSM error generated when trying to sign into Rapid with Firefox

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Firefox v103.0

### Steps to reproduce

opened up Rapid 2 link and clicked the log in logo. after attempting to sign in, error got generated
<img width="1268" alt="Screen Shot 2022-08-17 at 10 18 46 AM" src="https://user-images.githubusercontent.com/50604365/185204886-76579e0b-8481-4de4-978f-594621ad87bd.png">
 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&disable_features=indoor,boundaries,pistes,aerialways,power,past_future,others&id=w-887296317736347816&map=19.55/7.42779/3.94881

**Comment by bhousel** [comment]
Thanks for reporting, I am seeing this too.. 

I think it is constructing the redirect-url incorrectly.  For our use, it can always redirect back to `https://mapwith.ai/rapid/land.html`

**Comment by Bonkles** [comment]
Thanks for submitting your first bug @yeminator!

**Comment by Bonkles** [comment]
Fix commited in 1fa7517b0, and just went live for the alpha. @yeminator could you please try again after hard-refreshing your browser?

**Comment by Bonkles** [comment]
Fired up the alpha page, logged out. refreshed the page (just to clear any state). Logged back in successfully. Closing!

**Comment by akanjifb** [comment]
i can confirm that the above issue has been fixed!
