### ISSUE TITLE
Hotkey 'A' Double Assigned - Can't Continue Line

### ISSUE THREAD

**Issue by flow-enol** [facebookincubator/RapiD#554]
### Description

Can't continue a line from selected node. Instead, it selects the last RapID feature added says, "continued line" in a pop-up at the bottom left of the map. 

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Opera GX [LVL4 {core: 89.0.4447.98) (x86_64)}

### Steps to reproduce

Select a node at the end of a line - Press 'A'

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&id=w-1408501824605419685&map=20.30/34.00690/-117.92510

**Comment by Bonkles** [comment]
Re-tested- this issue has been fixed. Closing!
