### ISSUE TITLE
Unable To Click On Buttons Overlayed On Map After Completing An Edit Using A Tool

### ISSUE THREAD

**Issue by flow-enol** [facebookincubator/RapiD#556]
### Description

When a feature is created with one of the the map tools, the map overlay buttons (Add Features, Undo/Redo, Map Data, Background, etc.) don't work unless you click off of the newly created feature first. 

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Opera GX [LVL4 {core: 89.0.4447.98) (x86_64)}

### Steps to reproduce

Draw a line using the Line tool - Try clicking on Undo, one of the Add Feature tools, or Background buttons

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&id=w-11&map=20.57/34.00657/-117.92471

**Comment by Bonkles** [comment]
Fixed in `4b112f1d9`. The proper place for double-click handling is not in the draw behavior (as not all the draw behaviors need to detect it) but in the line drawing mode itself.
