### ISSUE TITLE
A Couple Bugs With "Undo"

### ISSUE THREAD

**Issue by flow-enol** [facebookincubator/RapiD#558]
### Description

(1) Using "Undo" after creating data using the Map Tool doesn't undo an edit on the first go. It doesn't start undo the edit until the second attempt.

> - The first attempt to "Undo" seems to be undoing the auto-zoom. 
> - If multiple geometries (lines for example) are drawn before "Undo", the first attempt still only adjust zoom without undoing an edit then continuing to undo there will be an auto-zoom plus undoing an edit with every separate feature.

(2) Undoing a line segment leaves a residual node. It only removes one node, instead of both nodes to completely remove the line. _The normal ID editor removes both nodes of a 2 node line._

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Opera GX [LVL4 {core: 89.0.4447.98) (x86_64)}

### Steps to reproduce

(1) Use the Line Tool to draw a line segment - Undo using the button at the top right or cmd+Z - No edits are undone. 

> Draw 3 separate line segments consecutively - After the third line begin to Undo until there are no more edits - Notice the auto-zoom when beginning to undo a new segment. 

(2) Use the Line Tool to draw a line segment - Undo (twice if the above issue still exists) - Only one of the nodes is removed.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&map=20.79/34.00637/-117.92466

**Comment by Bonkles** [comment]
More about this issue: we were getting our 'annotations' mixed up in the history, which was causing too many undos to be required in order to back changes out.

**Comment by Bonkles** [comment]
Fixed in `b662854`: Fix #258 by cleaning up the state transitions in the history that resulted from a line draw operation.
