### ISSUE TITLE
Unable to copy and paste features using Safari browser

### ISSUE THREAD

**Issue by VLD190** [facebookincubator/RapiD#562]
### Description

I tried to copy and paste a building and that shortcut function failed to work. I verified this bug by attempting to copy-paste ism data and proposed rapID data.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Safari v15.6

### Steps to reproduce

1) Select a building that has either a red outline (OSM data) or purple outline (proposed RapID data)
2) Press "command + C" to copy a building
3) Press "V" to paste
4) The paste function does not work.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.13/-18.95729/49.10903

**Comment by Bonkles** [comment]
Just re-tested this in safari, looks like it was fixed when I fixed #529 . Closing!
