### ISSUE TITLE
Unable to add a node to existing line or area feature using Safari Browser

### ISSUE THREAD

**Issue by VLD190** [facebookincubator/RapiD#563]
### Description

I attempted to correct the geometry of one of the buildings proposed by rapID, but I was unable to add a node to either an area or a line.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Safari v15.6

### Steps to reproduce

1) Select a pre-existing feature or a proposed feature by rapID
2) try adding a node anywhere to the feature where there is not already a node, by double-clicking it
3) notice that a node was not created.

This applies to the Safari browser.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-2183279203454838722&map=19.44/-18.94921/49.10990

**Comment by Bonkles** [comment]
Dupe of #566. Midpoints are back on the menu in our alpha 3 release coming soon!
