### ISSUE TITLE
Unable to add node to line or area feature

### ISSUE THREAD

**Issue by akanjifb** [facebookincubator/RapiD#566]
### Description

When digitizing new line or area features or modifying existing ones, im unable to add new nodes
<img width="536" alt="Screen Shot 2022-08-19 at 3 13 47 PM" src="https://user-images.githubusercontent.com/111467175/185713981-5cd3d1cf-dcd8-4b61-b82e-14387865a10b.png">
.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Firefox v103.0

### Steps to reproduce

Attempting to add nodes to any pre-existing feature. Also after adding new features, new nodes cant be created between original nodes.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&disable_features=indoor,boundaries,pistes,aerialways,power,past_future,others&map=20.12/37.80881/-122.26696

**Comment by jjiglesiasg** [comment]
Remains, it happen to me today

**Comment by Bonkles** [comment]
Closing as we have just fixed #538, which restores the midpoint functionality.
