### ISSUE TITLE
No zoom on double-click until move

### ISSUE THREAD

**Issue by mxxcon** [facebookincubator/RapiD#569]
### Description

When I double-click to zoom in the view doesn't update until i drag to move view, then the view updates and zooms in.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Firefox v103.0 on Windows 10

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.00/40.58023/-73.97116

**Comment by Bonkles** [comment]
Was able to repro this easily- thanks for the bug! It should be fixed in the next drop of the alpha, version `2.01`. 

Issue had to do with that attempts to disable zoom when double-clicking during a draw behavior. 

Fixed in commit `09919b08b`.
