### ISSUE TITLE
Country Request: Australia

### ISSUE THREAD

**Issue by tastrax** [facebookincubator/RapiD#57]
Requesting RapID for Australia. Especially our more rural and remote areas

**Comment by jeffdefacto** [comment]
Thanks for the request @tastrax 

I've added Australia to the list

**Comment by jeffdefacto** [comment]
Australia is now available.

Happy mapping!

**Comment by tastrax** [comment]
Thanks Folks - when will it be available in the downloads? https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries
