### ISSUE TITLE
Need to Restore the original feature filtering for OSM data

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#584]
Before FOSS4G, we disabled the map filtering checkboxes in the 'map data' sidebar, because they weren't implemented yet. We should implement them!

**Comment by Bonkles** [comment]
Fixed in `8cc59b26c`. 

Behold: 


![Image](https://user-images.githubusercontent.com/1887955/189440933-0134013c-6c37-4c24-8791-cdafe065ac64.gif)

**Comment by bhousel** [comment]
This is awesome!!!  Nice work 🔥
