### ISSUE TITLE
Adding Area feature can not be selected on RapiD v2 Alpha

### ISSUE THREAD

**Issue by asturksever** [facebookincubator/RapiD#586]
### Description

I can select Point and Line feature under add feature menu however Area feature can not be selected.

https://user-images.githubusercontent.com/28983926/189705853-bfd88df6-a3cf-4257-bc16-1ef866e94939.mov

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Chrome v105.0

### Steps to reproduce

- Go to this [link]([https://mapwith.ai/rapid-v2-alpha...](https://l.workplace.com/l.php?u=https%3A%2F%2Fmapwith.ai%2Frapid-v2-alpha%23background%3DMaxar-Premium%26datasets%3DfbRoads%2CmsBuildings%26disable_features%3Dboundaries%26map%3D19.45%2F14.81754%2F-90.91224&h=AT0eopidZkD3pwJe9slWdYBNfpC1fyD3HF-csoCYfnXKEkyyCPdDgxdBOfs01VmuTXprZqr2Vaf2iQjfqX-lKJFsJHNFYVc5EpRe3_BlGqrQQpll6w-FMMM_DDv9T_sX-v2f6wLjRnpVbjD3Bpdikf1zj-oSC8tSaQ&__tn__=-UK-R&c[0]=AT1E_VLUtYvC6nTGBi1bOqg-vLbcYfhBgnPLrXDFgJyul7aIzBym96f0SJdSMEeep-FOfRoHURmMCHnf5tRi7zkl6NJuGtwEOd24JUqcBZwRpc53p0E7PGfBy-flyNHKSPdNglT1DodI5vEDnWrIzDX-h98zamacrbTPEUtr5MUO59g5GGlIhLhC9qjG80GinHtv3cDRvABH_gNUqR-RD6Xw8aaOJA)) 
- Select adding area icon
- Area icon is not clickable 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.45/14.81754/-90.91224

**Comment by Bonkles** [comment]
Area drawing has been re-implemented and should be working for new point and existing point draws. Still needs a little TLC for adding points that are part of ways, but that will be tackled when I take a look at midpoint manipulation. 

1f5d682: Fixes to help ensure that the draw Node is replaced by the any pre-existing node we might click on.
3b48f3e: Finish basic bare-point area drawing, with correct undo/redo states and with fun diagrams!
