### ISSUE TITLE
Update Font Awesome/Maki dependencies

### ISSUE THREAD

**Issue by arch0345** [facebookincubator/RapiD#587]
With the release of [id-tagging-schema v3.5.0](https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#350), Font Awesome v6.1.1 or later is needed to display the [icon](https://fontawesome.com/v6/icons/child-reaching) for the [Childcare/Nursery preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/childcare.json) and the [icon](https://fontawesome.com/v6/icons/truck-fast) for the new [Runaway Truck Ramp preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/escape.json). Maki v8.0.0 or later is also needed to display the [icon](https://github.com/mapbox/maki/blob/main/icons/toll.svg) for the [Toll Booth preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/barrier/toll_booth.json).

As I mentioned in https://github.com/osmlab/osm-community-index/pull/567, the issue described in https://github.com/osmlab/osm-community-index/pull/508#issuecomment-1040522046 has been resolved in v6.2.0 ([changelog](https://fontawesome.com/docs/changelog)).

Importing `fontawesome` from `@fortawesome/fontawesome-svg-core` doesn't work after updating to v6.2.0, however I found that changing the `build_data` script to use named imports (in this case `{ library, icon, findIconDefinition }`) seems to fix this.

**Comment by bhousel** [comment]
Thanks for raising this @arch0345!  I'll apply your fix from the osm-community-index repo 👍

**Comment by bhousel** [comment]
I noticed when upgrading the Maki icons that they don't include separate `-11` and `-15` versions of the icons anymore.  

This requires some small code changes throughout RapiD (it actually makes things a little simpler), just noting here that I'm making those changes in both the main and v2 branches.
