### ISSUE TITLE
Buildings suggestions just dissapeared

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#589]
### Description

In the last week in a big area of #Bolivia all building suggestions just dissapeard. Road suggestions remains

### Version

1.1.9.

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Steps to reproduce

Just open this area as an example:

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries,power&map=16.75/-17.12017/-64.77326

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries,power&map=16.75/-17.12017/-64.77326

**Comment by DavidMetcalfe** [comment]
To add to this, it appears Microsoft Buildings outlines are no longer appearing in JOSM with the MapWithAI plugin, nor with the RapID v2 alpha website build. I have spot tested multiple locations across Canada, so this is not limited to Bolivia.

**Comment by DavidMetcalfe** [comment]
@Bonkles Thanks for the additional detail! Does the RapiD team have any contacts at Microsoft to alert them to this problem?

**Comment by Bonkles** [comment]
@DavidMetcalfe yes, Microsoft has been contacted- apologies for omitting that detail. We sent them a link to this very github issue, waiting to hear back.

**Comment by DavidMetcalfe** [comment]
Just an update from my end that full functionality seems to have been restored. Not sure if @jjiglesiasg has a different experience though.

**Comment by Bonkles** [comment]
Okay, this looks like it has been resolved! Closing.
