### ISSUE TITLE
Country request:Kosovo

### ISSUE THREAD

**Issue by msylka** [facebookincubator/RapiD#59]
Can you please process aerial images for Kosovo such that buildings and roads are available?

**Comment by jeffdefacto** [comment]
Thanks for the request @msylka and for adding it to the list.

Buildings are produced by Microsoft so it's up to them where they are made available.

**Comment by jeffdefacto** [comment]
Just an update, we had some issues generating Kosovo, but it is on the way.

**Comment by jeffdefacto** [comment]
Kosovo is now available.

Happy mapping!

**Comment by msylka** [comment]
> Kosovo is now available.
> 
> Happy mapping!

Thank you !
