### ISSUE TITLE
Building footprint overlaps with newly added building polygon

### ISSUE THREAD

**Issue by StephanGeorg** [facebookincubator/RapiD#601]
### Description

After adding a new building by clicking a suggested footprint it still shows it over the newly added building polygon. Before only the newly added building was shown which made it much easier to identify newly added buildings.

**Before**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/7861660/192472575-36c7bf4f-4d33-44c7-9fc7-001ec942430c.png">

**Adding the buildings**
<img width="730" alt="image" src="https://user-images.githubusercontent.com/7861660/192472691-aceab6ce-e145-4bc5-9c20-0e2e5340e5b6.png">

**After uploading the change to OSM**
<img width="800" alt="image" src="https://user-images.githubusercontent.com/7861660/192472868-fcebd0c2-3e75-4a01-809d-b2a00c6216f1.png">

### Version

1.1.9, and 2.0

### What browser are you seeing the problem on? What version are you running?

Chrome  105.0.5195.125

### Steps to reproduce

1. click on a building footprint
2. add it as a building polygon
3. upload your changes to OSM
4. switches back to edit mode

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.23/43.90543/12.92028

**Comment by Bonkles** [comment]
I think this is most likely a dupe of #592.

**Comment by StephanGeorg** [comment]
Duplicate of #592
