### ISSUE TITLE
Country Request: India

### ISSUE THREAD

**Issue by justinelliotmeyers** [facebookincubator/RapiD#61]
Hello! I would like to formally request roads for India. Thanks!
Justin

**Comment by jeffdefacto** [comment]
Thanks for the request! 

We've added it to the list

**Comment by chandusekhar** [comment]
> Thanks for the request!
> 
> We've added it to the list

Hello, any planned timelines available for the India roads. Thanks..

**Comment by jeffdefacto** [comment]
Hi chandusekhar,

We are currently predicting India road data and will then add it to our vectorization queue.

**Comment by jeffdefacto** [comment]
India is now available
