### ISSUE TITLE
fix BitmapText destroy() calls to once again work on children

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#620]
While updating to pixi.js v7, I ran into a bug in the 7.0.0.beta-3 release of pixi, and filed a bug. 

https://github.com/pixijs/pixijs/issues/8759

To work around this bug, all the `destroy()` calls being issued to BitmapText objects have been modified with the option `children:false`. This should be set back to `true` once we update to a newer version of the beta (at the time of this writing, none have been released).

**Comment by SuperSodaSea** [comment]
[pixi.js 7.0.0-beta.4](https://github.com/pixijs/pixijs/releases/tag/v7.0.0-beta.4) is out now, you can have a try!

**Comment by Bonkles** [comment]
Fixed in `8cda9a816`.
