### ISSUE TITLE
Country request: Ukraine

### ISSUE THREAD

**Issue by alexriabtsev** [facebookincubator/RapiD#63]
I'd like to request Ukraine be added to the queue. 
Cheers!

**Comment by jeffdefacto** [comment]
Thanks for the request! 

We've added it to the list

**Comment by Lyttym** [comment]
+1

**Comment by jeffdefacto** [comment]
Ukraine is now available.

Happy mapping!

**Comment by alexriabtsev** [comment]
> Ukraine is now available.
> 
> Happy mapping!

Thanks for great NY gift!
