### ISSUE TITLE
Streetside Imagery is throwing errors when bubbles are clicked on

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#645]
### Description

In addition, no image is presented in the photo viewer. 

Stack trace: 

```
Failed to load resource: the server responded with a status of 403 ()
streetside.js:283 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'face')
    at streetside.js:283:80
    at async Promise.all (index 0)
(anonymous) @ streetside.js:283
Promise.then (async)
selectImage @ streetside.js:876
(anonymous) @ streetside.js:104
Promise.then (async)
m @ streetside.js:102
(anonymous) @ on.js:3
```

### Version

1.1.8, 2.0-alpha2

### What browser are you seeing the problem on? What version are you running?

Chrome 107

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=past_future&map=18.00/44.06649/-103.18100&photo=streetside/1081871761&photo_overlay=streetside

**Comment by bhousel** [comment]
Yeah I think this is a dup of #567 ?
