### ISSUE TITLE
Check truncation of text with combining characters / diacritics

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#653]
This was raised on our Slack channel by @mapmeld 

> on Burmese labels, for points and lines, the lower part of the label may be clipped off (မဟာဗန္ဓုလလမ်း)

![Screen Shot 2022-11-16 at 10 50 07 AM](https://user-images.githubusercontent.com/38784/202228067-c860877b-42c5-4c1f-9578-36328ac0d697.png)
![Screen Shot 2022-11-16 at 10 50 15 AM](https://user-images.githubusercontent.com/38784/202228069-8ee0cd55-4e7b-431a-9007-9e89181268ca.png)

**Comment by bhousel** [comment]
I did some quick investigation last night and we can fix this a few ways..

Pixi has a test page where you can try out its font rendering:
[https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%22%23333%22%2C%22font[…]%99%E1%80%BA%22%2C%22background%22%3A%22%23787878%22%7D](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%22%23333%22%2C%22fontFamily%22%3A%22Helvetica%22%2C%22fontSize%22%3A13%2C%22fontWeight%22%3A600%2C%22lineHeight%22%3A10%2C%22lineJoin%22%3A%22bevel%22%2C%22miterLimit%22%3A5%2C%22stroke%22%3A%22white%22%2C%22strokeThickness%22%3A2.5%7D%2C%22text%22%3A%22%E1%80%99%E1%80%9F%E1%80%AC%E1%80%97%E1%80%94%E1%80%B9%E1%80%93%E1%80%AF%E1%80%9C%E1%80%9C%E1%80%99%E1%80%BA%22%2C%22background%22%3A%22%23787878%22%7D)

It's cut off there too, but if I increase the line height, it does show the full descender:
[https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%22%23333%22%2C%22font[…]%99%E1%80%BA%22%2C%22background%22%3A%22%23787878%22%7D](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%22%23333%22%2C%22fontFamily%22%3A%22Helvetica%22%2C%22fontSize%22%3A13%2C%22fontWeight%22%3A600%2C%22lineHeight%22%3A40%2C%22lineJoin%22%3A%22bevel%22%2C%22miterLimit%22%3A5%2C%22stroke%22%3A%22white%22%2C%22strokeThickness%22%3A2.5%7D%2C%22text%22%3A%22%E1%80%99%E1%80%9F%E1%80%AC%E1%80%97%E1%80%94%E1%80%B9%E1%80%93%E1%80%AF%E1%80%9C%E1%80%9C%E1%80%99%E1%80%BA%22%2C%22background%22%3A%22%23787878%22%7D)

Looks like adding padding to the texture also fixes the issue, but without moving the centerline of the text, maybe even better:
https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%22%23333%22%2C%22fontFamily%22%3A%22Helvetica%22%2C%22fontSize%22%3A13%2C%22fontWeight%22%3A600%2C%22lineJoin%22%3A%22bevel%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A4%2C%22stroke%22%3A%22white%22%2C%22strokeThickness%22%3A2.5%7D%2C%22text%22%3A%22%E1%80%99%E1%80%9F%E1%80%AC%E1%80%97%E1%80%94%E1%80%B9%E1%80%93%E1%80%AF%E1%80%9C%E1%80%9C%E1%80%99%E1%80%BA%E1%80%B8)%22%2C%22background%22%3A%22%23787878%22%7D

This issue gave me that hint:  https://github.com/pixijs/pixijs/issues/5864

**Comment by bhousel** [comment]
This was trickier than I thought, but I have it working pretty well now, both for basic Text next to pins, and on Ropes along lines.

<img width="838" alt="Screen Shot 2022-11-16 at 5 02 59 PM" src="https://user-images.githubusercontent.com/38784/202304207-929953f4-6e87-4fcf-aef2-7d254b17878e.png">

**Comment by mapmeld** [comment]
Awesome! 🙌 :shipit:
