### ISSUE TITLE
Country Request: Rwanda

### ISSUE THREAD

**Issue by mikelmaron** [facebookincubator/RapiD#67]
We're working with a partner to do road network accessibility analysis across Rwanda, using OpenStreetMap. They're interested to improve the underlying map. Can Rwanda be prioritized for generation and release?

Thanks!

**Comment by jeffdefacto** [comment]
We need to look over the data before officially announcing it, but, coincidentally, Rwanda is available as of this morning. :)

**Comment by allanwalkerit** [comment]
@jeffdefacto watching https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries with eager anticipation! Thank you!

**Comment by jeffdefacto** [comment]
Officially released!
