### ISSUE TITLE
Country Request: Madagascar

### ISSUE THREAD

**Issue by mikelmaron** [facebookincubator/RapiD#69]
We're working with a partner to do road network accessibility analysis in Madagascar, using OpenStreetMap. They're interested to improve the underlying map. Can Madagascar be prioritized for generation and release?

(maybe it's already done like [Rwanda](https://github.com/facebookincubator/RapiD/issues/67) ;) )

**Comment by jeffdefacto** [comment]
It hasn't been vectorized yet, but it is on the way

**Comment by jeffdefacto** [comment]
Madagascar is now available
