### ISSUE TITLE
Feature: AI generated buildings

### ISSUE THREAD

**Issue by amenk** [facebookincubator/RapiD#7]
Are there plans to add buildings as well?

**Comment by DrishT** [comment]
@amenk Eventually yes. With the way RapiD is built anyone can add the ability/tech to conflate any feature as long as there are corresponding integrity checks.

**Comment by rory** [comment]
> With the way RapiD is built anyone can add the ability/tech to conflate any feature as long as there are corresponding integrity checks.

Oh this sounds _very_ interesting, and I can't wait to learn more.  🙂

**Comment by danil-kirsanov** [comment]
Fundamentally, there is no difference between ML and non-ML sources of data, so in theory you can use the same RapiD workflow with the buildings. For the buildings, the conflation looks relatively straightforward -- roughly speaking, ensuring there is no intersections with the existing OSM buildings or building-like structures. You might also want to run the additional integrity checks and warn the user if the suggested building intersects a river or has very sharp angles, for example.
Saying this, we currently do not provide the support for the external datasets out of the box, but it might be an interesting direction if there is enough support. Is there a particular dataset you have in mind?

**Comment by amenk** [comment]
See https://github.com/facebookincubator/RapiD/pull/24

**Comment by gaoxm** [comment]
@amenk a testing version is available at https://mapwith.ai/rapid-sotm2019#background=EsriWorldImageryClarity&disable_features=boundaries&map=17.71/46.41819/-93.51503 in case you would like to try :)

**Comment by amenk** [comment]
Cool, thanks. I am wondering how well it will work with high buildings an not fully perpendicular imagery.

**Comment by bhousel** [comment]
This happened! 🎉
