### ISSUE TITLE
Country request: please add Ethiopia

### ISSUE THREAD

**Issue by amenk** [facebookincubator/RapiD#8]
There is still a lot of mapping to be done for Ethiopia..would be nice if you could add the country.

**Comment by DrishT** [comment]
Thanks @amenk! We have taken note of this request and will add it to our queue.

**Comment by zlavergne** [comment]
@amenk We now have data available in Ethiopia. Please refer to our [wiki](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki) for instruction on how to create projects and use RapiD!

**Comment by amenk** [comment]
Went to https://mapwith.ai/rapid#background=Maxar-FB&disable_features=boundaries&map=17.38/8.97740/37.86220 -- works .. thank you!
