### ISSUE TITLE
Proposed building outline disappears with specific key presses

### ISSUE THREAD

**Issue by DavidMetcalfe** [facebookincubator/RapiD#80]
This seems like it could be related to issue #11 but I'm opening a separate one just in case.

When selecting a proposed building outline, if I press either of the following key sequences, the building area disappears from view, requiring the editor to be reloaded (browser refresh):

- A -> R -> Esc
- A -> M -> Esc

**Before:** 
![image](https://user-images.githubusercontent.com/80915/70114361-18875980-1611-11ea-97e1-f00016e93375.png)

**After:**
![image](https://user-images.githubusercontent.com/80915/70114385-2c32c000-1611-11ea-8781-ba87dcb0f704.png)

**Following a browser refresh:**
![image](https://user-images.githubusercontent.com/80915/70114416-45d40780-1611-11ea-9e87-f130faecc305.png)

**Comment by Bonkles** [comment]
Definitely still a bug, but this only seems to happen SOME of the time, and even then, only when the key combo has been hit pretty fast. 

Am able to repro reliably on both Chrome and Safari. I believe that the problem may be the 'context.pop()' call that is in rotate.js' `cancel()` call, which is what is triggered when the a->r->esc key combo is pressed.

**Comment by bhousel** [comment]
Thanks for reporting @DavidMetcalfe 
reported https://github.com/openstreetmap/iD/issues/8441 
and fixed https://github.com/openstreetmap/iD/pull/8442

This will be fixed in the next version of RapiD.
