### ISSUE TITLE
Two points in Swimming Pool are very close together

### ISSUE THREAD

**Issue by DavidMetcalfe** [facebookincubator/RapiD#86]
While adding roads and buildings, I occasionally add in other features such as swimming pools. I've noticed that RapiD appears to strongly dislike swimming pools, whereas I don't see the same behaviour in the iD editor. 

**Example:** https://mapwith.ai/rapid#background=EsriWorldImageryClarity&disable_features=boundaries&id=w754205491&map=21.40/49.20709/-122.83644

**RapiD:**
![image](https://user-images.githubusercontent.com/80915/70516298-9b198880-1aeb-11ea-9892-6d28f6540935.png)

**iD:**
![image](https://user-images.githubusercontent.com/80915/70516327-a66cb400-1aeb-11ea-8b61-324f5bda7dad.png)

**Comment by jjiglesiasg** [comment]
This behavior is common for any area, who has very near nodes, not only for swimming pools

**Comment by bhousel** [comment]
I'm not sure when this changed, but RapiD is now using the same code as iD in the close_nodes check, so it's not raising  warnings about the swimming pool nodes being too close anymore. 

FWIW, here are the thresholds used in the validation (in meters):
https://github.com/facebookincubator/RapiD/blob/5e6f48b2f8dbd0c9b043feed71359a8745967719/modules/validations/close_nodes.js#L119-L125
