### ISSUE TITLE
Add Australia

### ISSUE THREAD

**Issue by herriotto** [facebookincubator/RapiD#88]
I dont see AU in your list of Countries, but Rapid is functioning and suggesting roads there

**Comment by jeffdefacto** [comment]
Hey @herriotto,

Thanks for the request. Australia is generated and roads are available we just haven't officially announced it yet. It will be part of next release.

**Comment by jeffdefacto** [comment]
Australia is now officially released

**Comment by herriotto** [comment]
Is there any timeline for getting the buildings released for AU? Thanks!
