### ISSUE TITLE
Building Request: Bolivia

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#91]
Much appreciated if the Building feature could be added to Bolivia.

Thanks and keep the good work. BsRgds

JJ

**Comment by jeffdefacto** [comment]
Currently, our only building support is from Microsoft's dataset so we do not have a time table on further support as it's up to them to create data.

This may change though in the near future and we appreciate the interest to help with prioritization.

**Comment by jjiglesiasg** [comment]
Thanks

**Comment by Bonkles** [comment]
Closing, as this is not something we have visibility into fixing.
