### ISSUE TITLE
maxar imagery

### ISSUE THREAD

**Issue by dalekunce** [facebookincubator/RapiD#92]
Suggest that for the time being maxar imagery is _not_ the default.

https://www.openstreetmap.org/user/@kevin_bullock/diary/391652

Maybe use either ESRI clarity or Facebook Maxar.

**Comment by jeffdefacto** [comment]
Definitely 

Once we merge in the iD 2.17 changes, the Maxar Premium and Standard layers will be removed for now.

**Comment by Bonkles** [comment]
Just pinged the iD maintainers about when they're releasing v3. As soon as iD v3 releases, we'll get our own v3-based release candidate into QA's hands, and have a new RapiD available ASAP!

**Comment by Bonkles** [comment]
Update: Since the iD v3-based RapiD release is a little further out than we thought, we did a point release to bring things up to date with iD v2.17. The Maxar background Layers are now a thing of the past.
